import './assets/styles/main.scss'
import { Inter } from 'next/font/google'
import classNames from 'classnames'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const className = classNames(inter.className, 'main')

  return (
    <html lang="en">
      <body className={className}>{children}</body>
    </html>
  )
}
